# Application name
spring.application.name=api-gateway

# ==============================
# Config Server
# ==============================
#spring.config.import=optional:configserver:http://localhost:8888
spring.config.import=optional:configserver:${CONFIG_SERVER_URL}
#spring.cloud.config.uri=${CONFIG_URL:http://config-server:8888}

## Server port
#server.port=8080
#
## ==============================
## Spring Cloud Gateway Routes
## ==============================
#
## User Service
#spring.cloud.gateway.routes[0].id=user-service
#spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**
#
## Activity Service
#spring.cloud.gateway.routes[1].id=activity-service
#spring.cloud.gateway.routes[1].uri=lb://ACTIVITY-SERVICE
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/activities/**
#
## AI Service
#spring.cloud.gateway.routes[2].id=ai-service
#spring.cloud.gateway.routes[2].uri=lb://AI-SERVICE
#spring.cloud.gateway.routes[2].predicates[0]=Path=/api/recommendations/**
#
## ==============================
## Eureka Client
## ==============================
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/