spring.application.name=user-service

#spring.config.import=optional:configserver:http://localhost:8888
spring.config.import=optional:configserver:${CONFIG_SERVER_URL}
#spring.config.import=${CONFIG_URL:http://config-server:8888}

#spring.datasource.url=jdbc:postgresql://localhost:5432/fitness-micro-user
#spring.datasource.username=postgres
#spring.datasource.password=SreeRama@005
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
#server.port=8081
#
##Configuration is required to locate the Eureka server
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/